#!/bin/bash
# FILENAME: millionaires_job_file

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR

apptainer exec --nv --writable sci-gpu.sif /bin/bash -c "
  cd /ezpc_dir/SCI/build/bin || exit 1
  ./millionaire-OT 1 & ./millionaire-OT 2
"
